#![cfg_attr(not(feature = "std"), no_std)]

use frame::prelude::*;
use vibly_primitives_common::{CapabilityMask, ContentRef, Hash256, IdentityNonce, TimestampMs};

/// Stable identifier for a root identity.
pub type IdentityId = Hash256;
/// Actor identifier used by pallets that model identity-backed actors.
pub type ActorId = IdentityId;
/// Stable identifier for an authorized key attached to an identity.
pub type KeyId = Hash256;
/// Stable identifier for an external transport binding.
pub type TransportBindingId = Hash256;
/// Application-defined key purpose code.
pub type PurposeCode = u16;

/// Allows a delegated key to update identity pointers.
pub const CAP_MANAGE_POINTERS: CapabilityMask = 1 << 0;
/// Allows a delegated key to bind, verify, or revoke transports.
pub const CAP_MANAGE_TRANSPORTS: CapabilityMask = 1 << 1;
/// Allows a delegated key to create and manage payment intents.
pub const CAP_MANAGE_PAYMENT: CapabilityMask = 1 << 2;
/// Allows a delegated key to satisfy any non-owner capability check.
pub const CAP_ADMIN: CapabilityMask = 1 << 3;

/// Lifecycle status for a root identity.
#[derive(
    Clone,
    Copy,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
pub enum IdentityStatus {
    /// The identity can be used for all supported operations.
    Active,
    /// Owner or recovery can unfreeze the identity, but delegated mutations are blocked.
    Frozen,
    /// The identity is permanently disabled for mutation and authorization checks.
    Disabled,
}

/// Human-facing purpose label for an authorized key.
#[derive(
    Clone,
    Copy,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
pub enum KeyPurpose {
    /// Reserved for the root owner account; not accepted as a delegated key.
    Owner,
    /// Reserved for the recovery account; not accepted as a delegated key.
    Recovery,
    /// General administration key.
    Admin,
    /// Session key with application-defined behavior.
    Session,
    /// Butler or agent-operation key.
    Butler,
    /// Finance key intended for payment-related workflows.
    Finance,
    /// Custom purpose code for application-specific delegation.
    Custom(PurposeCode),
}

/// Root identity record stored by `pallet-identity-core`.
///
/// The identity owns a small set of active content pointers and an optional recovery account.
/// Delegated access is stored separately in `AuthorizedKeyRecord`.
#[derive(
    Clone,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
#[scale_info(skip_type_params(MaxCidLen, MaxUriLen, AccountId))]
pub struct RootIdentity<AccountId, MaxCidLen: Get<u32>, MaxUriLen: Get<u32>> {
    /// Stable identity identifier generated by the pallet.
    pub identity_id: IdentityId,
    /// Account with full authority over the identity.
    pub owner: AccountId,
    /// Optional account allowed to rotate owner/recovery and unfreeze/disable the identity.
    pub recovery: Option<AccountId>,
    /// Current profile content pointer.
    pub active_profile: Option<ContentRef<MaxCidLen, MaxUriLen>>,
    /// Current agent registry content pointer.
    pub active_agent_registry: Option<ContentRef<MaxCidLen, MaxUriLen>>,
    /// Current authorization registry content pointer.
    pub active_auth_registry: Option<ContentRef<MaxCidLen, MaxUriLen>>,
    /// Current relation policy content pointer.
    pub active_relation_policy: Option<ContentRef<MaxCidLen, MaxUriLen>>,
    /// Lifecycle state controlling allowed mutations.
    pub status: IdentityStatus,
    /// Monotonic counter bumped when identity-owned state changes.
    pub nonce: IdentityNonce,
    /// Creation timestamp in milliseconds.
    pub created_at: TimestampMs,
    /// Last mutation timestamp in milliseconds.
    pub updated_at: TimestampMs,
}

/// Delegated account record for identity-scoped authorization.
///
/// Owner and recovery accounts are represented directly on `RootIdentity`; this record is only
/// for additional accounts with explicit capability bits.
#[derive(
    Clone,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
#[scale_info(skip_type_params(AccountId))]
pub struct AuthorizedKeyRecord<AccountId> {
    /// Stable key identifier derived from identity and account.
    pub key_id: KeyId,
    /// Identity this key authorizes against.
    pub identity_id: IdentityId,
    /// Account granted delegated access.
    pub account: AccountId,
    /// Human-facing purpose label.
    pub purpose: KeyPurpose,
    /// Bitmask of capabilities granted to the account.
    pub capability_mask: CapabilityMask,
    /// Optional expiration timestamp in milliseconds.
    pub expires_at: Option<TimestampMs>,
    /// Optional revocation timestamp; active records have `None`.
    pub revoked_at: Option<TimestampMs>,
    /// Creation timestamp in milliseconds.
    pub created_at: TimestampMs,
}

/// External communication channel kind for identity bindings.
#[derive(
    Clone,
    Copy,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
pub enum TransportKind {
    /// Matrix user or room locator.
    Matrix,
    /// Discord account or channel locator.
    Discord,
    /// Telegram account or chat locator.
    Telegram,
    /// Email address locator.
    Email,
    /// Application-defined transport kind.
    Custom(u16),
}

/// Verification status for a bound external transport account.
#[derive(
    Clone,
    Copy,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
pub enum TransportBindingStatus {
    /// The identity has requested the binding but owner/recovery has not verified it.
    Pending,
    /// The binding has been verified for this identity.
    Verified,
    /// The binding is no longer valid for this identity.
    Revoked,
}

/// External transport binding attached to an identity.
///
/// Bindings are indexed both by generated binding id and by an identity/transport/account
/// locator hash so the same transport account cannot be bound twice for one identity.
#[derive(
    Clone,
    Eq,
    PartialEq,
    Encode,
    Decode,
    DecodeWithMemTracking,
    RuntimeDebug,
    TypeInfo,
    MaxEncodedLen,
)]
#[scale_info(skip_type_params(MaxTransportAccountLen, MaxCidLen, MaxUriLen))]
pub struct TransportBinding<
    MaxTransportAccountLen: Get<u32>,
    MaxCidLen: Get<u32>,
    MaxUriLen: Get<u32>,
> {
    /// Stable binding identifier generated by the pallet.
    pub binding_id: TransportBindingId,
    /// Identity that owns this binding.
    pub identity_id: IdentityId,
    /// Transport namespace for the account bytes.
    pub transport: TransportKind,
    /// Bounded account locator bytes in the transport namespace.
    pub account: BoundedVec<u8, MaxTransportAccountLen>,
    /// Optional off-chain proof pointer.
    pub proof_ref: Option<ContentRef<MaxCidLen, MaxUriLen>>,
    /// Verification lifecycle state.
    pub status: TransportBindingStatus,
    /// Creation timestamp in milliseconds.
    pub created_at: TimestampMs,
    /// Last mutation timestamp in milliseconds.
    pub updated_at: TimestampMs,
}

/// Cross-pallet identity authorization surface.
///
/// Payment and future application pallets use this trait instead of reading identity storage
/// directly. Implementations must enforce identity state and capability checks consistently.
pub trait IdentityAccess<AccountId> {
    /// Returns whether the identity exists.
    fn identity_exists(identity_id: &IdentityId) -> bool;
    /// Returns the owner account for settlement or custody flows.
    fn owner_account(identity_id: &IdentityId) -> Option<AccountId>;
    /// Ensures `who` may manage payment intents for `identity_id`.
    fn ensure_can_manage_payment(identity_id: &IdentityId, who: &AccountId) -> DispatchResult;
    /// Ensures `who` may claim payment intents for `identity_id`.
    fn ensure_can_claim_payment(identity_id: &IdentityId, who: &AccountId) -> DispatchResult;
}
